main: net.okocraft.playermanager.PlayerManager
name: ${project.artifactId}
version: ${project.version}
description: "Execute some actions when renamed players joined."
authors: [okocraft]
api-version: "1.13"

permissions:
  playermanager.admin:
    default: op

commands:
  playermanager:
    description: "Command for PlayerManager"
    aliases: [pmanager, pman, pm]
    permission: playermanager.admin
