name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: "Execute some actions when renamed players joined."
authors: [LazyGon]
api-version: "1.15"

commands:
  altmanager:
    description: "Command for altmanager"
    aliases: [am, alt]
    permission: altmanager
permissions:
  altmanager.*:
    default: op
    children:
      altmanager: true
  altmanager:
    default: true
  altmanager.namechange.*:
    default: op
    children:
      altmanager.namechange: true
      altmanager.namechange.previousname: true
  altmanager.namechange:
    default: true
  altmanager.namechange.previousname:
    default: true
  altmanager.alt.*:
    default: op
    childres:
      altmanager.alt: true
      altmanager.alt.search: true
      altmanager.alt.getip: true
      altmanager.alt.uniqueaccess: true
  altmanager.alt:
    default: true
  altmanager.alt.search:
    default: true
  altmanager.alt.getip:
    default: op
  altmanager.alt.uniqueaccess:
    default: true
  
